language: node_js
node_js:
  - 10
before_script:
  - npm install -g firebase-tools
  - npm install -g @vue/cli
script:
  - npm run test:unit
  - npm run build
  - . ci/deploy.sh
after_script:
  - cat ./coverage/lcov.info | coveralls
after_success:
  - firebase use starcitizen-tools
  - firebase deploy --token $FIREBASE_TOKEN
