#!/bin/sh

# write env var in a file
FILE="dist/.env"

/bin/cat <<EOM >$FILE
VUE_APP_I18N_LOCALE=fr
VUE_APP_I18N_FALLBACK_LOCALE=en
VUE_APP_FIREBASE_APIKEY=$FIREBASE_APIKEY
VUE_APP_FIREBASE_AUTHDOMAIN=$FIREBASE_AUTHDOMAIN
VUE_APP_FIREBASE_DATABASEURL=$FIREBASE_DATABASEURL
VUE_APP_FIREBASE_MESSAGINGSENDERID=$FIREBASE_MESSAGINGSENDERID
VUE_APP_FIREBASE_PROJECTID=$FIREBASE_PROJECTID
VUE_APP_FIREBASE_STORAGEBUCKET=$FIREBASE_STORAGEBUCKET
EOM